### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dev-jet** [deathmarine/Luyten#118]
java.lang.IllegalStateException: Wrong magic number: 2004318021
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:337)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

**Comment by deathmarine** [comment]
I would say the jar is either corrupt, or the class could be encrypted, the software could be decrypting classes and loading them later as a sort of obfuscation. Either way I can only reproduce this intentionally, by renaming a binary file to class and putting it in a jar.
You may have to do a little more investigation, look for a class extending Classloader and pulling resources from the jar. I once wrote a wrapper that would decrypt and load each class and after phoning home and authenticating using a public and private key. Either way there is something else going on here.
