### ISSUE TITLE
unable to decompile

### ISSUE THREAD

**Issue by hoaivan** [deathmarine/Luyten#124]
```
java.lang.IllegalStateException: Invalid BootstrapMethods attribute entry: 2 additional arguments required for method java/lang/invoke/StringConcatFactory.makeConcatWithConstants, but only 1 specified.
	at com.strobel.assembler.ir.Error.invalidBootstrapMethodEntry(Error.java:243)
	at com.strobel.assembler.ir.MetadataReader.readAttributeCore(MetadataReader.java:255)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:260)
	at com.strobel.assembler.ir.MetadataReader.inflateAttributes(MetadataReader.java:412)
	at com.strobel.assembler.metadata.ClassFileReader.visitAttributes(ClassFileReader.java:1133)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:438)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:365)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.FileSaver.doSaveJarDecompiled(FileSaver.java:183)
	at us.deathmarine.luyten.FileSaver.access$300(FileSaver.java:45)
	at us.deathmarine.luyten.FileSaver$4.run(FileSaver.java:112)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by deathmarine** [comment]
Procyon errors are being closed.
