### ISSUE TITLE
Unable to open file!

### ISSUE THREAD

**Issue by VakareX** [deathmarine/Luyten#135]
java.lang.IllegalArgumentException: Argument 'value' must be in the range [1, 18], but value was: 111.
	at com.strobel.core.VerifyArgument.inRange(VerifyArgument.java:346)
	at com.strobel.assembler.ir.ConstantPool$Tag.fromValue(ConstantPool.java:532)
	at com.strobel.assembler.ir.ConstantPool.read(ConstantPool.java:362)
	at com.strobel.assembler.metadata.JarTypeLoader.getInternalNameFromClassFile(JarTypeLoader.java:105)
	at com.strobel.assembler.metadata.JarTypeLoader.tryLoadType(JarTypeLoader.java:78)
	at us.deathmarine.luyten.LuytenTypeLoader.tryLoadType(LuytenTypeLoader.java:25)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:120)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

![image](https://user-images.githubusercontent.com/37980134/40724438-be75f8ec-6429-11e8-9bdc-cd7646eecfcc.png)

**Comment by greenozon** [comment]
would be nice if you upload your  java .class file that leads to this issue...
