### ISSUE TITLE
 BUG

### ISSUE THREAD

**Issue by StarOfLion** [deathmarine/Luyten#136]
##MALFORMED
this is message below
```java
java.lang.IllegalArgumentException: MALFORMED
	at java.util.zip.ZipCoder.toString(Unknown Source)
	at java.util.zip.ZipFile.getZipEntry(Unknown Source)
	at java.util.zip.ZipFile.access$900(Unknown Source)
	at java.util.zip.ZipFile$1.nextElement(Unknown Source)
	at java.util.zip.ZipFile$1.nextElement(Unknown Source)
	at java.util.jar.JarFile$1.nextElement(Unknown Source)
	at java.util.jar.JarFile$1.nextElement(Unknown Source)
	at us.deathmarine.luyten.JarEntryFilter.getEntriesWithoutInnerClasses(JarEntryFilter.java:41)
	at us.deathmarine.luyten.Model$6.run(Model.java:696)
	at java.lang.Thread.run(Unknown Source)
```
That will report this error when I drag the zip package to the window,but sometimes the zip package doesn't report the error.

**Comment by StarOfLion** [comment]
it seems that will go wrong when i use the jd-gui to save all reources

**Comment by TheKalin** [comment]
@StarOfLion  can you share the zip with us ?
