### ISSUE TITLE
NullPointerException in BreakTargetRelocation.convertToContinue() method

### ISSUE THREAD

**Issue by znakeeye** [deathmarine/Luyten#137]
Opened jar (from dex2jar). "Save All"... At 82% I got this error :(

java.lang.NullPointerException
	at com.strobel.decompiler.languages.java.ast.transforms.BreakTargetRelocation.convertToContinue(BreakTargetRelocation.java:377)
	at com.strobel.decompiler.languages.java.ast.transforms.BreakTargetRelocation.run(BreakTargetRelocation.java:191)
	at com.strobel.decompiler.languages.java.ast.transforms.BreakTargetRelocation.runForMethod(BreakTargetRelocation.java:107)
	at com.strobel.decompiler.languages.java.ast.transforms.BreakTargetRelocation.visitMethodDeclaration(BreakTargetRelocation.java:59)
	at com.strobel.decompiler.languages.java.ast.transforms.BreakTargetRelocation.visitMethodDeclaration(BreakTargetRelocation.java:29)
	at com.strobel.decompiler.languages.java.ast.MethodDeclaration.acceptVisitor(MethodDeclaration.java:85)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitTypeDeclaration(DepthFirstAstVisitor.java:236)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclaration(ContextTrackingVisitor.java:52)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclaration(ContextTrackingVisitor.java:28)
	at com.strobel.decompiler.languages.java.ast.TypeDeclaration.acceptVisitor(TypeDeclaration.java:90)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitCompilationUnit(DepthFirstAstVisitor.java:241)
	at com.strobel.decompiler.languages.java.ast.CompilationUnit.acceptVisitor(CompilationUnit.java:81)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.run(ContextTrackingVisitor.java:84)
	at com.strobel.decompiler.languages.java.ast.transforms.TransformationPipeline.runTransformationsUntil(TransformationPipeline.java:91)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.runTransformations(AstBuilder.java:99)
	at com.strobel.decompiler.languages.java.JavaLanguage.runTransforms(JavaLanguage.java:97)
	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:72)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
	at us.deathmarine.luyten.FileSaver.doSaveJarDecompiled(FileSaver.java:192)
	at us.deathmarine.luyten.FileSaver.access$300(FileSaver.java:45)
	at us.deathmarine.luyten.FileSaver$4.run(FileSaver.java:112)
	at java.lang.Thread.run(Unknown Source)

**Comment by TheKalin** [comment]
@znakeeye can you share the jar file with us? I will try to reproduce it.
