### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by libingtong** [deathmarine/Luyten#144]
java.lang.IllegalStateException: Invalid BootstrapMethods attribute entry: 2 additional arguments required for method java/lang/invoke/StringConcatFactory.makeConcatWithConstants, but only 1 specified.
	at com.strobel.assembler.ir.Error.invalidBootstrapMethodEntry(Error.java:243)
	at com.strobel.assembler.ir.MetadataReader.readAttributeCore(MetadataReader.java:255)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:260)
	at com.strobel.assembler.ir.MetadataReader.inflateAttributes(MetadataReader.java:412)
	at com.strobel.assembler.metadata.ClassFileReader.visitAttributes(ClassFileReader.java:1133)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:438)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:365)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
	at com.strobel.assembler.metadata.MetadataSystem.resolveCore(MetadataSystem.java:76)
	at com.strobel.assembler.metadata.MetadataResolver.resolve(MetadataResolver.java:104)
	at com.strobel.assembler.metadata.CoreMetadataFactory$UnresolvedType.resolve(CoreMetadataFactory.java:614)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:274)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:255)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:153)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:149)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createMethod(AstBuilder.java:644)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:532)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:499)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:141)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:130)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addType(AstBuilder.java:105)
	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:71)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
	at us.deathmarine.luyten.DecompilerLinkProvider.generateContent(DecompilerLinkProvider.java:97)
	at us.deathmarine.luyten.OpenFile.decompileWithNavigationLinks(OpenFile.java:469)
	at us.deathmarine.luyten.OpenFile.decompile(OpenFile.java:442)
	at us.deathmarine.luyten.Model.extractClassToTextPane(Model.java:420)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:339)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

**Comment by jluehe** [comment]
@libingtong, has there been any resolution to this?
