### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by gitrobtest** [deathmarine/Luyten#153]

**Comment by gitrobtest** [comment]
java.lang.NullPointerException
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:324)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:153)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:149)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createParameters(AstBuilder.java:161)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createMethod(AstBuilder.java:642)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:532)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:499)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:141)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:130)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addType(AstBuilder.java:105)
	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:71)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
	at us.deathmarine.luyten.FindAllBox$FindButton$1.run(FindAllBox.java:219)
