### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by nightstar311** [deathmarine/Luyten#154]
java.lang.IllegalArgumentException: Argument 'type' cannot be null.
	at com.strobel.core.VerifyArgument.notNull(VerifyArgument.java:37)
	at com.strobel.assembler.ir.attributes.LocalVariableTableEntry.<init>(LocalVariableTableEntry.java:41)
	at com.strobel.assembler.ir.MetadataReader.readAttributeCore(MetadataReader.java:180)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:260)
	at com.strobel.assembler.ir.MetadataReader.readAttribute(MetadataReader.java:50)
	at com.strobel.assembler.ir.MetadataReader.readAttributes(MetadataReader.java:40)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:202)
	at com.strobel.assembler.ir.MetadataReader.inflateAttribute(MetadataReader.java:368)
	at com.strobel.assembler.ir.MetadataReader.inflateAttributes(MetadataReader.java:345)
	at com.strobel.assembler.metadata.ClassFileReader.defineMethods(ClassFileReader.java:977)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:440)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:365)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

**Comment by greenozon** [comment]
it'd be a big plus for author if you attach the input file.
but most probably, according to your stack trace the issue is inside the engine (code name Procyon) which is not part of Luyten SW ..

**Comment by yulu86** [comment]
Luyten is just a GUI for [Proycon](https://bitbucket.org/mstrobel/procyon), I think it's a bug of Procyon, can't be solved in Luyten.
