### ISSUE TITLE
java.lang.IllegalStateException: Wrong magic number: 1883791669

### ISSUE THREAD

**Issue by zuodh** [deathmarine/Luyten#160]
java.lang.IllegalStateException: Wrong magic number: 1883791669
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:337)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

**Comment by yulu86** [comment]
1883791669 seems like a chinese mobile phone number
