### ISSUE TITLE
java.lang.IllegalStateException: Invalid BootstrapMethods attribute entry: 2 additional arguments required for method java/lang/invoke/StringConcatFactory.makeConcatWithConstants, but only 1 specified.

### ISSUE THREAD

**Issue by bugreport3** [deathmarine/Luyten#185]
When opening a particular .class file on the latest release of Luyten (v0.5.4), I receive the following error message, and then the .class does not decompile:

> Unable to open file!
> 
> java.lang.IllegalStateException:
>
> Invalid BootstrapMethods attribute entry: 2 additional arguments required for method java/lang/invoke/StringConcatFactory.makeConcatWithConstants, but only 1 specified.
> 	at com.strobel.assembler.ir.Error.invalidBootstrapMethodEntry(Error.java:243)
> 	at com.strobel.assembler.ir.MetadataReader.readAttributeCore(MetadataReader.java:267)
> 	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:261)
> 	at com.strobel.assembler.ir.MetadataReader.inflateAttributes(MetadataReader.java:424)
> 	at com.strobel.assembler.metadata.ClassFileReader.visitAttributes(ClassFileReader.java:1134)
> 	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:439)
> 	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:366)
> 	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
> 	at com.strobel.assembler.metadata.MetadataSystem.resolveCore(MetadataSystem.java:81)
> 	at com.strobel.assembler.metadata.MetadataResolver.resolve(MetadataResolver.java:104)
> 	at com.strobel.assembler.metadata.CoreMetadataFactory$UnresolvedType.resolve(CoreMetadataFactory.java:616)
> 	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:294)
> 	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:173)
> 	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:169)
> 	at com.strobel.decompiler.languages.java.ast.AstBuilder.createField(AstBuilder.java:622)
> 	at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:544)
> 	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:519)
> 	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:161)
> 	at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:150)
> 	at com.strobel.decompiler.languages.java.ast.AstBuilder.addType(AstBuilder.java:125)
> 	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:71)
> 	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
> 	at us.deathmarine.luyten.DecompilerLinkProvider.generateContent(DecompilerLinkProvider.java:97)
> 	at us.deathmarine.luyten.OpenFile.decompileWithNavigationLinks(OpenFile.java:494)
> 	at us.deathmarine.luyten.OpenFile.decompile(OpenFile.java:467)
> 	at us.deathmarine.luyten.Model.extractClassToTextPane(Model.java:420)
> 	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:339)
> 	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

**Comment by i0xHeX** [comment]
Same, using jdk 11, also on startup:
```
java.lang.IllegalStateException: Invalid BootstrapMethods attribute entry: 2 additional arguments required for method java/lang/invoke/StringConcatFactory.makeConcatWithConstants, but only 1 specified.
	at com.strobel.assembler.ir.Error.invalidBootstrapMethodEntry(Error.java:243)
	at com.strobel.assembler.ir.MetadataReader.readAttributeCore(MetadataReader.java:267)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:261)
	at com.strobel.assembler.ir.MetadataReader.inflateAttributes(MetadataReader.java:424)
	at com.strobel.assembler.metadata.ClassFileReader.visitAttributes(ClassFileReader.java:1134)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:439)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:366)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.resolveCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.resolve(MetadataResolver.java:104)
	at com.strobel.assembler.metadata.CoreMetadataFactory$UnresolvedType.resolve(CoreMetadataFactory.java:616)
	at com.strobel.assembler.metadata.MetadataResolver.resolve(MetadataResolver.java:91)
	at com.strobel.assembler.metadata.CoreMetadataFactory$UnresolvedType.resolve(CoreMetadataFactory.java:616)
	at com.strobel.assembler.metadata.ClassFileReader.populateNamedInnerTypes(ClassFileReader.java:698)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:442)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:366)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model$9.run(Model.java:968)
```

**Comment by jackoelv** [comment]
JDK 8, same as you.

**Comment by hallojuhu** [comment]
Same, SDK 12
java.lang.IllegalStateException: Invalid BootstrapMethods attribute entry: 2 additional arguments required for method java/lang/invoke/StringConcatFactory.makeConcatWithConstants, but only 1 specified.
	at com.strobel.assembler.ir.Error.invalidBootstrapMethodEntry(Error.java:243)
	at com.strobel.assembler.ir.MetadataReader.readAttributeCore(MetadataReader.java:267)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:261)
	at com.strobel.assembler.ir.MetadataReader.inflateAttributes(MetadataReader.java:424)
	at com.strobel.assembler.metadata.ClassFileReader.visitAttributes(ClassFileReader.java:1134)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:439)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:366)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.resolveCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.resolve(MetadataResolver.java:104)
	at com.strobel.assembler.metadata.CoreMetadataFactory$UnresolvedType.resolve(CoreMetadataFactory.java:616)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:294)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:173)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:169)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createField(AstBuilder.java:622)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:544)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:519)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:161)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:150)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addType(AstBuilder.java:125)
	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:71)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
	at us.deathmarine.luyten.DecompilerLinkProvider.generateContent(DecompilerLinkProvider.java:97)
	at us.deathmarine.luyten.OpenFile.decompileWithNavigationLinks(OpenFile.java:494)
	at us.deathmarine.luyten.OpenFile.decompile(OpenFile.java:467)
	at us.deathmarine.luyten.Model.extractClassToTextPane(Model.java:420)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:339)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)


anyone an Idea how to solve thise issue?
-Hallojuhu
