### ISSUE TITLE
java.lang.IllegalStateException: Invalid BootstrapMethods attribute entry

### ISSUE THREAD

**Issue by Ruskonert** [deathmarine/Luyten#207]
When I running this application, The exception occurred following traces:
```
java.lang.IllegalStateException: Invalid BootstrapMethods attribute entry: 2 additional arguments required for method java/lang/invoke/StringConcatFactory.makeConcatWithConstants, but only 1 specified.
	at com.strobel.assembler.ir.Error.invalidBootstrapMethodEntry(Error.java:244)
	at com.strobel.assembler.ir.MetadataReader.readAttributeCore(MetadataReader.java:267)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:261)
	at com.strobel.assembler.ir.MetadataReader.inflateAttributes(MetadataReader.java:426)
	at com.strobel.assembler.metadata.ClassFileReader.visitAttributes(ClassFileReader.java:1134)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:439)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:377)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.resolveCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.resolve(MetadataResolver.java:104)
	at com.strobel.assembler.metadata.CoreMetadataFactory$UnresolvedType.resolve(CoreMetadataFactory.java:616)
	at com.strobel.assembler.metadata.MetadataHelper.isRawType(MetadataHelper.java:1581)
	at com.strobel.assembler.metadata.MetadataHelper$SameTypeVisitor.visitClassType(MetadataHelper.java:2369)
	at com.strobel.assembler.metadata.MetadataHelper$SameTypeVisitor.visitClassType(MetadataHelper.java:2322)
	at com.strobel.assembler.metadata.TypeDefinition.accept(TypeDefinition.java:183)
	at com.strobel.assembler.metadata.MetadataHelper$SameTypeVisitor.visit(MetadataHelper.java:2336)
	at com.strobel.assembler.metadata.MetadataHelper.isSameType(MetadataHelper.java:1411)
	at com.strobel.assembler.metadata.TypeReference.equals(TypeReference.java:118)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:504)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:161)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:150)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addType(AstBuilder.java:125)
	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:71)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
	at us.deathmarine.luyten.DecompilerLinkProvider.generateContent(DecompilerLinkProvider.java:97)
	at us.deathmarine.luyten.OpenFile.decompileWithNavigationLinks(OpenFile.java:494)
	at us.deathmarine.luyten.OpenFile.decompile(OpenFile.java:467)
	at us.deathmarine.luyten.Model.extractClassToTextPane(Model.java:420)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:339)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)
```
There's no problem running, but it's noisy 😨

**Comment by belingueres** [comment]
I had this exception too.

**Comment by jkkong** [comment]
me too
