### ISSUE TITLE
SHA-256 digest error 

### ISSUE THREAD

**Issue by paynexss** [deathmarine/Luyten#212]
java.lang.SecurityException: SHA-256 digest error for 
	at sun.security.util.ManifestEntryVerifier.verify(Unknown Source)
	at java.util.jar.JarVerifier.processEntry(Unknown Source)
	at java.util.jar.JarVerifier.update(Unknown Source)
	at java.util.jar.JarVerifier$VerifierStream.read(Unknown Source)
	at com.strobel.assembler.metadata.JarTypeLoader.tryLoadType(JarTypeLoader.java:66)
	at us.deathmarine.luyten.LuytenTypeLoader.tryLoadType(LuytenTypeLoader.java:25)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:120)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

**Comment by paynexss** [comment]
resolved
