### ISSUE TITLE
luyten-0.5.4 crash in macOS 10.13

### ISSUE THREAD

**Issue by a1203991686** [deathmarine/Luyten#216]
Crash when I try to launch "luyten-0.5.4.jar" or "luyten-0.5.4.app" which I downloaded from realease. Then I download from Homebrew, but it still crash.
When I launch "luyten-0.5.4.jar", it shows me that info:

```java
java.lang.IllegalStateException: Invalid BootstrapMethods attribute entry: 2 additional arguments required for method java/lang/invoke/StringConcatFactory.makeConcatWithConstants, but only 1 specified.
	at com.strobel.assembler.ir.Error.invalidBootstrapMethodEntry(Error.java:244)
	at com.strobel.assembler.ir.MetadataReader.readAttributeCore(MetadataReader.java:267)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:261)
	at com.strobel.assembler.ir.MetadataReader.inflateAttributes(MetadataReader.java:426)
	at com.strobel.assembler.metadata.ClassFileReader.visitAttributes(ClassFileReader.java:1134)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:439)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:377)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.resolveCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.resolve(MetadataResolver.java:104)
	at com.strobel.assembler.metadata.CoreMetadataFactory$UnresolvedType.resolve(CoreMetadataFactory.java:616)
	at com.strobel.assembler.metadata.MetadataResolver.resolve(MetadataResolver.java:91)
	at com.strobel.assembler.metadata.CoreMetadataFactory$UnresolvedType.resolve(CoreMetadataFactory.java:616)
	at com.strobel.assembler.metadata.ClassFileReader.populateNamedInnerTypes(ClassFileReader.java:698)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:442)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:377)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model$9.run(Model.java:968)

```

Java version: Java SE12.0.1
luyten: 0.5.4
OS: macOS10.13
Github release and Homebrew crash both have this problem.

**Comment by a1203991686** [comment]
Sorry, I made a mistake.
Now, the situation is:
Luythen.app is still crashed, whatever I download it from where. And Luythen.app is still showing no info.
But Luythen.jar show me the worn info, but it can work normally.
