### ISSUE TITLE
unable to decompile file

### ISSUE THREAD

**Issue by moshichua** [deathmarine/Luyten#219]
java.lang.IllegalStateException: Wrong magic number: 52
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:337)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.FileSaver.doSaveJarDecompiled(FileSaver.java:183)
	at us.deathmarine.luyten.FileSaver.access$300(FileSaver.java:45)
	at us.deathmarine.luyten.FileSaver$4.run(FileSaver.java:112)
	at java.lang.Thread.run(Unknown Source)

**Comment by deathmarine** [comment]
Procyon errors are being closed. The file is not a java class binary or is encrypted.
