### ISSUE TITLE
Unable to open file!

### ISSUE THREAD

**Issue by True-han** [deathmarine/Luyten#225]
I can't open module-info.class.
Stacktrace:
```
java.lang.IllegalArgumentException: Argument 'value' must be in the range [1, 18], but value was: 19.
	at com.strobel.core.VerifyArgument.inRange(VerifyArgument.java:347)
	at com.strobel.assembler.ir.ConstantPool$Tag.fromValue(ConstantPool.java:532)
	at com.strobel.assembler.ir.ConstantPool.read(ConstantPool.java:362)
	at com.strobel.assembler.metadata.JarTypeLoader.getInternalNameFromClassFile(JarTypeLoader.java:105)
	at com.strobel.assembler.metadata.JarTypeLoader.tryLoadType(JarTypeLoader.java:78)
	at us.deathmarine.luyten.LuytenTypeLoader.tryLoadType(LuytenTypeLoader.java:25)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:125)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

```

**Comment by soonroad** [comment]
the same issue.

**Comment by terminated-star** [comment]
same here
