### ISSUE TITLE
BootstrapMethods attribute entry

### ISSUE THREAD

**Issue by magicjva** [deathmarine/Luyten#231]
java.lang.IllegalStateException: Invalid BootstrapMethods attribute entry: 2 additional arguments required for method java/lang/invoke/StringConcatFactory.makeConcatWithConstants, but only 1 specified.
	at com.strobel.assembler.ir.Error.invalidBootstrapMethodEntry(Error.java:244)
	at com.strobel.assembler.ir.MetadataReader.readAttributeCore(MetadataReader.java:280)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:261)
	at com.strobel.assembler.ir.MetadataReader.inflateAttributes(MetadataReader.java:439)
	at com.strobel.assembler.metadata.ClassFileReader.visitAttributes(ClassFileReader.java:1134)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:439)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:377)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

**Comment by magicjva** [comment]
please fix

**Comment by timurgen** [comment]
Looks like this issue is not related to Luyten but Procyon library used to decompile java classes.

**Comment by abma** [comment]
-> https://bitbucket.org/mstrobel/procyon/downloads/

overwriting the contents of luyten-0.5.4.jar with the contents of
 https://bitbucket.org/mstrobel/procyon/downloads/procyon-decompiler-0.5.36.jar

expect MANIFEST-INF/MANIFEST.MF makes it work for me!

**Comment by abma** [comment]
#220 should fix this as well...
