### ISSUE TITLE
 Invalid BootstrapMethods attribute entry

### ISSUE THREAD

**Issue by greenozon** [deathmarine/Luyten#246]
Full error:

`java.lang.IllegalStateException: Invalid BootstrapMethods attribute entry: 2 additional arguments required for method java/lang/invoke/StringConcatFactory.makeConcatWithConstants, but only 1 specified.
	at com.strobel.assembler.ir.Error.invalidBootstrapMethodEntry(Error.java:244)
	at com.strobel.assembler.ir.MetadataReader.readAttributeCore(MetadataReader.java:280)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:261)
	at com.strobel.assembler.ir.MetadataReader.inflateAttributes(MetadataReader.java:439)
	at com.strobel.assembler.metadata.ClassFileReader.visitAttributes(ClassFileReader.java:1134)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:439)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:377)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:355)
	at us.deathmarine.luyten.Model$6$1.run(Model.java:721)
`

**Comment by SylviaLee89** [comment]
I noticed that there is a similar problem at this project. Perhaps we can refer to these issue: https://github.com/deathmarine/Luyten/issues/252, https://github.com/deathmarine/Luyten/issues/190, https://github.com/deathmarine/Luyten/issues/124 and https://github.com/deathmarine/Luyten/issues/14,  to find more context about the bug.
