### ISSUE TITLE
Unable to open file!

### ISSUE THREAD

**Issue by yfeic** [deathmarine/Luyten#250]
When I open a jar file. it comes Error.
=======================
java.lang.IllegalStateException: Wrong magic number: 2004318020
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:338)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:349)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:277)

**Comment by yfeic** [comment]
I found the byte code was encrypted
