### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by jans2002** [deathmarine/Luyten#251]
Luyten 0.5.4
procyon Version 0.5.36
The callstack is :
------------------------------
java.lang.ClassCastException: com.strobel.assembler.metadata.CoreMetadataFactory$MethodSignature cannot be cast to com.strobel.assembler.metadata.MethodReference
	at com.strobel.decompiler.languages.java.utilities.TypeUtilities.getExpectedTypeByParent(TypeUtilities.java:365)
	at com.strobel.decompiler.languages.java.utilities.RedundantCastUtility$IsRedundantVisitor.visitCastExpression(RedundantCastUtility.java:344)
	at com.strobel.decompiler.languages.java.utilities.RedundantCastUtility$IsRedundantVisitor.visitCastExpression(RedundantCastUtility.java:167)
	at com.strobel.decompiler.languages.java.ast.CastExpression.acceptVisitor(CastExpression.java:55)
	at com.strobel.decompiler.languages.java.utilities.RedundantCastUtility.isCastRedundant(RedundantCastUtility.java:67)
   ....

	at us.deathmarine.luyten.Model.extractClassToTextPane(Model.java:420)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:339)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

**Comment by hola-holo** [comment]
I noticed that there is a similar problem at https://github.com/deathmarine/Luyten/issues/194, https://github.com/deathmarine/Luyten/issues/67, https://github.com/deathmarine/Luyten/issues/199 and https://github.com/deathmarine/Luyten/issues/208. According to these issues, all Procyon errors are being closed.
