### ISSUE TITLE
Error in opening jar package

### ISSUE THREAD

**Issue by onlyGuo** [deathmarine/Luyten#253]
`java.nio.BufferUnderflowException
	at com.strobel.assembler.metadata.Buffer.verifyReadableBytes(Buffer.java:387)
	at com.strobel.assembler.metadata.Buffer.readUnsignedByte(Buffer.java:214)
	at com.strobel.assembler.ir.ConstantPool.read(ConstantPool.java:362)
	at com.strobel.assembler.metadata.JarTypeLoader.getInternalNameFromClassFile(JarTypeLoader.java:105)
	at com.strobel.assembler.metadata.JarTypeLoader.tryLoadType(JarTypeLoader.java:78)
	at us.deathmarine.luyten.LuytenTypeLoader.tryLoadType(LuytenTypeLoader.java:25)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:125)
	at com.strobel.assembler.metadata.MetadataSystem.resolveCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.resolve(MetadataResolver.java:104)
	at com.strobel.assembler.metadata.CoreMetadataFactory$UnresolvedType.resolve(CoreMetadataFactory.java:616)
	at com.strobel.assembler.metadata.ClassFileReader.populateNamedInnerTypes(ClassFileReader.java:698)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:442)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:377)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)
`
The package: 
[hs-temperature-calculate-inv.jar.zip](https://github.com/deathmarine/Luyten/files/5032968/hs-temperature-calculate-inv.jar.zip)

**Comment by onlyGuo** [comment]
And my system is Mac.
