### ISSUE TITLE
Decompiling: java.lang.IllegalStateException: Wrong magic number: 808508590

### ISSUE THREAD

**Issue by BaseMax** [deathmarine/Luyten#266]
Hi there,

I have a `.exe` software. This can open as **zip** file. So i rename `.exe` to `.zip` and `.zip` to `.jar`.

```
java.lang.IllegalStateException: Wrong magic number: 808508590
  at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:337)
  at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
  at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
  at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
  at us.deathmarine.luyten.FileSaver.doSaveJarDecompiled(FileSaver.java:183)

  at us.deathmarine.luyten.FileSaver.access$300(FileSaver.java:45)
  at us.deathmarine.luyten.FileSaver$4.run(FileSaver.java:112)
  at java.lang.Thread.run(Unknown Source)
```

![photo_2020-12-26_08-17-44](https://user-images.githubusercontent.com/2658040/103146050-e33c3500-4758-11eb-8bc6-84aba8e88143.jpg)

Download this software/jar to debug and future tests: [sample-software.zip](https://github.com/deathmarine/Luyten/files/5742718/sample-software.zip)

Thanks in advance for any guide.

Regards,
Max

**Comment by greenozon** [comment]
>I have a .exe software. This can open as zip file. So i rename .exe to .zip and .zip to .jar.

Your zip (sample-software.zip)  has all the java .class files encrypted
Instead of CAFEBABE signature  all the .class files having "VLX200" signature

It means you have to decrypt it first

Thus, I guess .exe is not a simple exe, it does the actual decription

**Comment by DannyRavi** [comment]
it is about Protect Java Code from Decompiling . check [vlinx](https://vlinx.io) product.
