### ISSUE TITLE
BufferUnderflowException

### ISSUE THREAD

**Issue by GhostFace54** [deathmarine/Luyten#268]
`java.nio.BufferUnderflowException
	at com.strobel.assembler.metadata.Buffer.verifyReadableBytes(Buffer.java:387)
	at com.strobel.assembler.metadata.Buffer.readInt(Buffer.java:231)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:335)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)
`

What would this error be and is there a chance that anyone can patch/fix it?

**Comment by FreshMix** [comment]
Hello! Please help, the same problem

**Comment by greenozon** [comment]
To beginwith - a common practice is to attach your .jar/.class file that leads to an issue
2) most probably this is an issue not in Luyten, but in backend engine, but that need to be proven

**Comment by GhostFace54** [comment]
[sample.zip](https://github.com/deathmarine/Luyten/files/5769603/sample.zip)
