### ISSUE TITLE
java.lang.IllegalStateException: Wrong magic number: 609111379

### ISSUE THREAD

**Issue by phildev4** [deathmarine/Luyten#270]
java.lang.IllegalStateException: Wrong magic number: 609111379
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:338)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)
Maybe decompile protection?

**Comment by greenozon** [comment]
Please attach your input file, in this case the chance will be higher
