### ISSUE TITLE
java.lang.Exception: Unable to resolve type. 	at us.deathmarine.luyten.Model.extractClassToTextPane(Model.java:402) 	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:356) 	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

### ISSUE THREAD

**Issue by youyuddk** [deathmarine/Luyten#275]
java.lang.Exception: Unable to resolve type.
	at us.deathmarine.luyten.Model.extractClassToTextPane(Model.java:402)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:356)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

what should i do

**Comment by greenozon** [comment]
Please attach your input file, in this case the chance will be higher
