### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by 2b2names** [deathmarine/Luyten#286]
hello so im using the thing im trying to open a file but it says

java.lang.IllegalStateException: Wrong magic number: 3216895935
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:338)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

pls help

**Comment by greenozon** [comment]
>Wrong magic number: 3216895935

in hex this is BFBDEFBF

it means your java class file is not valid, most probably it is encrypted/packed/etc

Magic number should be CAFEBABE
ref to https://en.wikipedia.org/wiki/Java_class_file   for details
