### ISSUE TITLE
Caused by: java.util.zip.ZipException: invalid LOC heade

### ISSUE THREAD

**Issue by javadoge** [deathmarine/Luyten#291]
java.lang.reflect.UndeclaredThrowableException: An unhandled checked exception occurred.
	at com.strobel.core.ExceptionUtilities.asRuntimeException(ExceptionUtilities.java:33)
	at com.strobel.assembler.metadata.JarTypeLoader.tryLoadType(JarTypeLoader.java:91)
	at us.deathmarine.luyten.LuytenTypeLoader.tryLoadType(LuytenTypeLoader.java:25)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:125)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at com.strobel.assembler.metadata.JarTypeLoader.tryLoadType(JarTypeLoader.java:66)
	... 6 more

**Comment by ThexXTURBOXx** [comment]
This looks like your zip file is broken

**Comment by greenozon** [comment]
Please attach your zipo for inspection
