### ISSUE TITLE
Error when using Find All

### ISSUE THREAD

**Issue by xdadova** [deathmarine/Luyten#300]
java.util.IllegalFormatConversionException: x != java.lang.Float
	at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source)
	at java.util.Formatter$FormatSpecifier.printInteger(Unknown Source)
	at java.util.Formatter$FormatSpecifier.print(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.lang.String.format(Unknown Source)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitPrimitiveExpression(JavaOutputVisitor.java:1805)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitPrimitiveExpression(JavaOutputVisitor.java:51)
	at com.strobel.decompiler.languages.java.ast.PrimitiveExpression.acceptVisitor(PrimitiveExpression.java:102)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitBinaryOperatorExpression(JavaOutputVisitor.java:2054)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitBinaryOperatorExpression(JavaOutputVisitor.java:51)
	at com.strobel.decompiler.languages.java.ast.BinaryOperatorExpression.acceptVisitor(BinaryOperatorExpression.java:88)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitReturnStatement(JavaOutputVisitor.java:1123)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitReturnStatement(JavaOutputVisitor.java:51)
	at com.strobel.decompiler.languages.java.ast.ReturnStatement.acceptVisitor(ReturnStatement.java:57)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitBlockStatement(JavaOutputVisitor.java:956)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.writeEmbeddedStatement(JavaOutputVisitor.java:470)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitIfElseStatement(JavaOutputVisitor.java:1050)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitIfElseStatement(JavaOutputVisitor.java:51)
	at com.strobel.decompiler.languages.java.ast.IfElseStatement.acceptVisitor(IfElseStatement.java:83)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitBlockStatement(JavaOutputVisitor.java:956)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitBlockStatement(JavaOutputVisitor.java:51)
	at com.strobel.decompiler.languages.java.ast.BlockStatement.acceptVisitor(BlockStatement.java:72)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitTryCatchStatement(JavaOutputVisitor.java:2516)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitTryCatchStatement(JavaOutputVisitor.java:51)
	at com.strobel.decompiler.languages.java.ast.TryCatchStatement.acceptVisitor(TryCatchStatement.java:73)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitBlockStatement(JavaOutputVisitor.java:956)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitBlockStatement(JavaOutputVisitor.java:51)
	at com.strobel.decompiler.languages.java.ast.BlockStatement.acceptVisitor(BlockStatement.java:72)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitLabeledStatement(JavaOutputVisitor.java:1111)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitLabeledStatement(JavaOutputVisitor.java:51)
	at com.strobel.decompiler.languages.java.ast.LabeledStatement.acceptVisitor(LabeledStatement.java:68)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitBlockStatement(JavaOutputVisitor.java:956)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitBlockStatement(JavaOutputVisitor.java:51)
	at com.strobel.decompiler.languages.java.ast.BlockStatement.acceptVisitor(BlockStatement.java:72)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitLabeledStatement(JavaOutputVisitor.java:1111)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitLabeledStatement(JavaOutputVisitor.java:51)
	at com.strobel.decompiler.languages.java.ast.LabeledStatement.acceptVisitor(LabeledStatement.java:68)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.writeMethodBody(JavaOutputVisitor.java:552)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitMethodDeclaration(JavaOutputVisitor.java:1427)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitMethodDeclaration(JavaOutputVisitor.java:51)
	at com.strobel.decompiler.languages.java.ast.MethodDeclaration.acceptVisitor(MethodDeclaration.java:85)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitTypeDeclaration(JavaOutputVisitor.java:1680)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitTypeDeclaration(JavaOutputVisitor.java:51)
	at com.strobel.decompiler.languages.java.ast.TypeDeclaration.acceptVisitor(TypeDeclaration.java:90)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitCompilationUnit(JavaOutputVisitor.java:1698)
	at com.strobel.decompiler.languages.java.JavaOutputVisitor.visitCompilationUnit(JavaOutputVisitor.java:51)
	at com.strobel.decompiler.languages.java.ast.CompilationUnit.acceptVisitor(CompilationUnit.java:81)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.generateCode(AstBuilder.java:844)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:60)
	at us.deathmarine.luyten.FindAllBox$FindButton$1.run(FindAllBox.java:234)

**Comment by xdadova** [comment]
Doesn't happo
