### ISSUE TITLE
Error searching a .jar file.

### ISSUE THREAD

**Issue by markell6** [deathmarine/Luyten#308]
While performing a find all search in a .jar file for the following string "plugin-api", the following error was displayed.

java.lang.IllegalArgumentException: Argument 'value' must be in the range [1, 18], but value was: 19.
	at com.strobel.core.VerifyArgument.inRange(VerifyArgument.java:347)
	at com.strobel.assembler.ir.ConstantPool$Tag.fromValue(ConstantPool.java:532)
	at com.strobel.assembler.ir.ConstantPool.read(ConstantPool.java:362)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:344)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.FindAllBox$FindButton$1.run(FindAllBox.java:221)

**Comment by ThexXTURBOXx** [comment]
Looks like an issue in procyon rather than Luyten
