### ISSUE TITLE
java.lang.IllegalStateException: Invalid BootstrapMethods attribute entry: 2 additional arguments required for method java/lang/invoke/StringConcatFactory.makeConcatWithConstants, but only 1 specified.

### ISSUE THREAD

**Issue by being1943** [deathmarine/Luyten#317]
java.lang.IllegalStateException: Invalid BootstrapMethods attribute entry: 2 additional arguments required for method java/lang/invoke/StringConcatFactory.makeConcatWithConstants, but only 1 specified.
	at com.strobel.assembler.ir.Error.invalidBootstrapMethodEntry(Error.java:244)
	at com.strobel.assembler.ir.MetadataReader.readAttributeCore(MetadataReader.java:280)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:261)
	at com.strobel.assembler.ir.MetadataReader.inflateAttributes(MetadataReader.java:439)
	at com.strobel.assembler.metadata.ClassFileReader.visitAttributes(ClassFileReader.java:1134)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:439)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:377)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:129)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:86)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)
help?

**Comment by 1534834526** [comment]
### 1、Please temporarily open luyten using the following method
   java -jar luyten-0.5.4.exe
### 2、Then open your class file
![image](https://github.com/deathmarine/Luyten/assets/40166027/4b308c10-ab11-410a-acff-a38598404a8f)

**Comment by vrosu** [comment]
This works also with java -jar luyten-0.5.4.jar. Maybe do we dare to dream this will be fixed sometime :D ?

**Comment by Hexyart** [comment]
Hello,
I didn’t understand the method I tried with the cmd and it doesn’t work 
the gap is still there can you help me?

**Comment by JodyBoyy** [comment]
same issue.

**Comment by JodyBoyy** [comment]
+ 1

**Comment by greenozon** [comment]
please attach your samples, thx
