### ISSUE TITLE
 Wrong magic number: 752774482

### ISSUE THREAD

**Issue by luogq2** [deathmarine/Luyten#324]
error open file ，log：
java.lang.IllegalStateException: Wrong magic number: 752774482
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:337)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

**Comment by HarizEzzat** [comment]
![photo_6246779527304952797_y](https://github.com/deathmarine/Luyten/assets/149940170/1cbd9dec-554c-4e58-aa12-efd36bef7e61)
