### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by capricornstone** [deathmarine/Luyten#61]
java.lang.NullPointerException
	at com.strobel.decompiler.languages.java.ast.DefiniteAssignmentAnalysis.setAnalyzedRange(DefiniteAssignmentAnalysis.java:117)
	at com.strobel.decompiler.languages.java.ast.DefiniteAssignmentAnalysis.setAnalyzedRange(DefiniteAssignmentAnalysis.java:108)
	at com.strobel.decompiler.languages.java.ast.transforms.ConvertLoopsTransform.transformForEachInArray(ConvertLoopsTransform.java:906)
	at com.strobel.decompiler.languages.java.ast.transforms.ConvertLoopsTransform.visitWhileStatement(ConvertLoopsTransform.java:89)
	at com.strobel.decompiler.languages.java.ast.transforms.ConvertLoopsTransform.visitWhileStatement(ConvertLoopsTransform.java:42)
	at com.strobel.decompiler.languages.java.ast.WhileStatement.acceptVisitor(WhileStatement.java:64)
	at com.strobel.decompiler.languages.java.ast.transforms.ConvertLoopsTransform.visitChildren(ConvertLoopsTransform.java:56)
	at com.strobel.decompiler.languages.java.ast.transforms.ConvertLoopsTransform.visitChildren(ConvertLoopsTransform.java:42)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitBlockStatement(DepthFirstAstVisitor.java:96)
	at com.strobel.decompiler.languages.java.ast.BlockStatement.acceptVisitor(BlockStatement.java:72)
	at com.strobel.decompiler.languages.java.ast.transforms.ConvertLoopsTransform.visitChildren(ConvertLoopsTransform.java:56)
	at com.strobel.decompiler.languages.java.ast.transforms.ConvertLoopsTransform.visitChildren(ConvertLoopsTransform.java:42)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitMethodDeclaration(DepthFirstAstVisitor.java:206)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitMethodDeclaration(ContextTrackingVisitor.java:64)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitMethodDeclaration(ContextTrackingVisitor.java:28)
	at com.strobel.decompiler.languages.java.ast.MethodDeclaration.acceptVisitor(MethodDeclaration.java:85)
	at com.strobel.decompiler.languages.java.ast.transforms.ConvertLoopsTransform.visitChildren(ConvertLoopsTransform.java:56)
	at com.strobel.decompiler.languages.java.ast.transforms.ConvertLoopsTransform.visitChildren(ConvertLoopsTransform.java:42)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitTypeDeclaration(DepthFirstAstVisitor.java:236)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclaration(ContextTrackingVisitor.java:52)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclaration(ContextTrackingVisitor.java:28)
	at com.strobel.decompiler.languages.java.ast.TypeDeclaration.acceptVisitor(TypeDeclaration.java:90)
	at com.strobel.decompiler.languages.java.ast.transforms.ConvertLoopsTransform.visitChildren(ConvertLoopsTransform.java:56)
	at com.strobel.decompiler.languages.java.ast.transforms.ConvertLoopsTransform.visitChildren(ConvertLoopsTransform.java:42)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitCompilationUnit(DepthFirstAstVisitor.java:241)
	at com.strobel.decompiler.languages.java.ast.CompilationUnit.acceptVisitor(CompilationUnit.java:81)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.run(ContextTrackingVisitor.java:84)
	at com.strobel.decompiler.languages.java.ast.transforms.TransformationPipeline.runTransformationsUntil(TransformationPipeline.java:91)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.runTransformations(AstBuilder.java:99)
	at com.strobel.decompiler.languages.java.JavaLanguage.runTransforms(JavaLanguage.java:97)
	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:72)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
	at us.deathmarine.luyten.DecompilerLinkProvider.generateContent(DecompilerLinkProvider.java:96)
	at us.deathmarine.luyten.OpenFile.decompileWithNavigationLinks(OpenFile.java:497)
	at us.deathmarine.luyten.OpenFile.decompile(OpenFile.java:470)
	at us.deathmarine.luyten.Model.extractClassToTextPane(Model.java:359)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:278)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:234)

**Comment by deathmarine** [comment]
Do you have an example file, or was there something you selected that caused this NPE?
