### ISSUE TITLE
java.lang.IllegalStateException: Wrong magic number: 2004318021

### ISSUE THREAD

**Issue by dev-jet** [deathmarine/Luyten#64]
```
java.lang.IllegalStateException: Wrong magic number: 2004318021
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:337)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:277)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:234)

**Comment by deathmarine** [comment]
See reference at #82
