### ISSUE TITLE
I got a "Argument type cannot be null" using this

### ISSUE THREAD

**Issue by Lothrazar** [deathmarine/Luyten#66]
~~~
java.lang.IllegalArgumentException: Argument 'type' cannot be null.
	at com.strobel.core.VerifyArgument.notNull(VerifyArgument.java:37)
	at com.strobel.assembler.ir.attributes.LocalVariableTableEntry.<init>(LocalVariableTableEntry.java:41)
	at com.strobel.assembler.ir.MetadataReader.readAttributeCore(MetadataReader.java:180)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:260)
	at com.strobel.assembler.ir.MetadataReader.readAttribute(MetadataReader.java:50)
	at com.strobel.assembler.ir.MetadataReader.readAttributes(MetadataReader.java:40)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:202)
	at com.strobel.assembler.ir.MetadataReader.inflateAttribute(MetadataReader.java:368)
	at com.strobel.assembler.ir.MetadataReader.inflateAttributes(MetadataReader.java:345)
	at com.strobel.assembler.metadata.ClassFileReader.defineMethods(ClassFileReader.java:977)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:440)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:365)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
	at com.strobel.assembler.metadata.MetadataSystem.resolveCore(MetadataSystem.java:76)
	at com.strobel.assembler.metadata.MetadataResolver.resolve(MetadataResolver.java:104)
	at com.strobel.assembler.metadata.CoreMetadataFactory$UnresolvedType.resolve(CoreMetadataFactory.java:614)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:274)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:235)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:153)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:149)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createField(AstBuilder.java:602)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:524)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:499)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:141)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:556)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:499)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:141)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:130)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addType(AstBuilder.java:105)
	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:71)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
	at us.deathmarine.luyten.FileSaver.doSaveJarDecompiled(FileSaver.java:198)
	at us.deathmarine.luyten.FileSaver.access$300(FileSaver.java:51)
	at us.deathmarine.luyten.FileSaver$4.run(FileSaver.java:118)
	at java.lang.Thread.run(Unknown Source)

**Comment by deathmarine** [comment]
Procyon Development has halted.

**Comment by deathmarine** [comment]
Procyon errors are being closed.
