### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by demkom58** [deathmarine/Luyten#72]
```
java.lang.NullPointerException
    at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.makeKey(EclipseEnumSwitchRewriterTransform.java:303)
    at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.visitSwitchStatement(EclipseEnumSwitchRewriterTransform.java:103)
    at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.visitSwitchStatement(EclipseEnumSwitchRewriterTransform.java:48)
    at com.strobel.decompiler.languages.java.ast.SwitchStatement.acceptVisitor(SwitchStatement.java:66)
    at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
    at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitBlockStatement(DepthFirstAstVisitor.java:96)
    at com.strobel.decompiler.languages.java.ast.BlockStatement.acceptVisitor(BlockStatement.java:72)
    at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
    at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitMethodDeclaration(DepthFirstAstVisitor.java:206)
    at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitMethodDeclaration(ContextTrackingVisitor.java:64)
    at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.visitMethodDeclaration(EclipseEnumSwitchRewriterTransform.java:172)
    at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.visitMethodDeclaration(EclipseEnumSwitchRewriterTransform.java:48)
    at com.strobel.decompiler.languages.java.ast.MethodDeclaration.acceptVisitor(MethodDeclaration.java:85)
    at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
    at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitTypeDeclaration(DepthFirstAstVisitor.java:236)
    at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclaration(ContextTrackingVisitor.java:52)
    at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclaration(ContextTrackingVisitor.java:28)
    at com.strobel.decompiler.languages.java.ast.TypeDeclaration.acceptVisitor(TypeDeclaration.java:90)
    at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
    at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitCompilationUnit(DepthFirstAstVisitor.java:241)
    at com.strobel.decompiler.languages.java.ast.CompilationUnit.acceptVisitor(CompilationUnit.java:81)
    at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform.run(EclipseEnumSwitchRewriterTransform.java:44)
    at com.strobel.decompiler.languages.java.ast.transforms.TransformationPipeline.runTransformationsUntil(TransformationPipeline.java:91)
    at com.strobel.decompiler.languages.java.ast.AstBuilder.runTransformations(AstBuilder.java:99)
    at com.strobel.decompiler.languages.java.JavaLanguage.runTransforms(JavaLanguage.java:97)
    at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:72)
    at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
    at us.deathmarine.luyten.DecompilerLinkProvider.generateContent(DecompilerLinkProvider.java:97)
    at us.deathmarine.luyten.OpenFile.decompileWithNavigationLinks(OpenFile.java:469)
    at us.deathmarine.luyten.OpenFile.decompile(OpenFile.java:442)
    at us.deathmarine.luyten.Model.extractClassToTextPane(Model.java:368)
    at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:287)
    at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:243)
```
java.lang.NullPointerException

Pastebin: https://pastebin.com/Uz8TJiXY
Class files: https://mega.nz/#!h5EikLDD!uqmGF2epU3WdMPHjIeZsBpAoe3R9t1WHM8uuhZKxsXw

**Comment by deathmarine** [comment]
Procyon errors are being closed.
