### ISSUE TITLE
java.lang.IllegalStateException: malformed input around byte 8

### ISSUE THREAD

**Issue by dev-jet** [deathmarine/Luyten#73]
```
java.lang.IllegalStateException: malformed input around byte 8
	at com.strobel.assembler.metadata.Buffer.readUtf8(Buffer.java:200)
	at com.strobel.assembler.ir.ConstantPool.read(ConstantPool.java:366)
	at com.strobel.assembler.metadata.JarTypeLoader.getInternalNameFromClassFile(JarTypeLoader.java:105)
	at com.strobel.assembler.metadata.JarTypeLoader.tryLoadType(JarTypeLoader.java:78)
	at us.deathmarine.luyten.LuytenTypeLoader.tryLoadType(LuytenTypeLoader.java:25)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:120)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:286)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:243)

**Comment by deathmarine** [comment]
Procyon errors are being closed.
