### ISSUE TITLE
NullPointerException ... at java.lang.Thread.run(Thread.java:745)

### ISSUE THREAD

**Issue by Brynnwynna** [deathmarine/Luyten#77]
This is for release 0.5.2. It looks similar to the two other NullPointerException issues (#61, #72) posted:
```
java.lang.NullPointerException
	at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.makeKey(EclipseEnumSwitchRewriterTransform.java:303)
	at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.visitSwitchStatement(EclipseEnumSwitchRewriterTransform.java:103)
	at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.visitSwitchStatement(EclipseEnumSwitchRewriterTransform.java:48)
	at com.strobel.decompiler.languages.java.ast.SwitchStatement.acceptVisitor(SwitchStatement.java:66)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitBlockStatement(DepthFirstAstVisitor.java:96)
	at com.strobel.decompiler.languages.java.ast.BlockStatement.acceptVisitor(BlockStatement.java:72)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitMethodDeclaration(DepthFirstAstVisitor.java:206)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitMethodDeclaration(ContextTrackingVisitor.java:64)
	at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.visitMethodDeclaration(EclipseEnumSwitchRewriterTransform.java:172)
	at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.visitMethodDeclaration(EclipseEnumSwitchRewriterTransform.java:48)
	at com.strobel.decompiler.languages.java.ast.MethodDeclaration.acceptVisitor(MethodDeclaration.java:85)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitEnumValueDeclaration(DepthFirstAstVisitor.java:366)
	at com.strobel.decompiler.languages.java.ast.EnumValueDeclaration.acceptVisitor(EnumValueDeclaration.java:47)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitTypeDeclaration(DepthFirstAstVisitor.java:236)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclaration(ContextTrackingVisitor.java:52)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclaration(ContextTrackingVisitor.java:28)
	at com.strobel.decompiler.languages.java.ast.TypeDeclaration.acceptVisitor(TypeDeclaration.java:90)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitCompilationUnit(DepthFirstAstVisitor.java:241)
	at com.strobel.decompiler.languages.java.ast.CompilationUnit.acceptVisitor(CompilationUnit.java:81)
	at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform.run(EclipseEnumSwitchRewriterTransform.java:44)
	at com.strobel.decompiler.languages.java.ast.transforms.TransformationPipeline.runTransformationsUntil(TransformationPipeline.java:91)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.runTransformations(AstBuilder.java:99)
	at com.strobel.decompiler.languages.java.JavaLanguage.runTransforms(JavaLanguage.java:97)
	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:72)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
	at us.deathmarine.luyten.FileSaver.doSaveJarDecompiled(FileSaver.java:192)
	at us.deathmarine.luyten.FileSaver.access$300(FileSaver.java:45)
	at us.deathmarine.luyten.FileSaver$4.run(FileSaver.java:112)
	at java.lang.Thread.run(Thread.java:745)
```
The jar file I tried to decompile: https://mega.nz/#!KodwEIzJ!Z8xHOCo8_AMNIlPILFg5Je2Q2mUKSVnd1bGeAbUvUf4
It stopped at `com/base/game/character/attributes/AttributeLevelCorruption.class` when doing "Decompile All", but continues after that, with the same error in two other places (`com/base/game/character/effects/Transformation.class`, `com/base/game/character/effects/StatusEffect.class`).

If I click to open them directly from "Structure", then I receive this error:
```
java.lang.NullPointerException
	at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.makeKey(EclipseEnumSwitchRewriterTransform.java:303)
	at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.visitSwitchStatement(EclipseEnumSwitchRewriterTransform.java:103)
	at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.visitSwitchStatement(EclipseEnumSwitchRewriterTransform.java:48)
	at com.strobel.decompiler.languages.java.ast.SwitchStatement.acceptVisitor(SwitchStatement.java:66)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitBlockStatement(DepthFirstAstVisitor.java:96)
	at com.strobel.decompiler.languages.java.ast.BlockStatement.acceptVisitor(BlockStatement.java:72)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitIfElseStatement(DepthFirstAstVisitor.java:126)
	at com.strobel.decompiler.languages.java.ast.IfElseStatement.acceptVisitor(IfElseStatement.java:83)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitBlockStatement(DepthFirstAstVisitor.java:96)
	at com.strobel.decompiler.languages.java.ast.BlockStatement.acceptVisitor(BlockStatement.java:72)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitMethodDeclaration(DepthFirstAstVisitor.java:206)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitMethodDeclaration(ContextTrackingVisitor.java:64)
	at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.visitMethodDeclaration(EclipseEnumSwitchRewriterTransform.java:172)
	at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform$Visitor.visitMethodDeclaration(EclipseEnumSwitchRewriterTransform.java:48)
	at com.strobel.decompiler.languages.java.ast.MethodDeclaration.acceptVisitor(MethodDeclaration.java:85)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitEnumValueDeclaration(DepthFirstAstVisitor.java:366)
	at com.strobel.decompiler.languages.java.ast.EnumValueDeclaration.acceptVisitor(EnumValueDeclaration.java:47)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitTypeDeclaration(DepthFirstAstVisitor.java:236)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclaration(ContextTrackingVisitor.java:52)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclaration(ContextTrackingVisitor.java:28)
	at com.strobel.decompiler.languages.java.ast.TypeDeclaration.acceptVisitor(TypeDeclaration.java:90)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitCompilationUnit(DepthFirstAstVisitor.java:241)
	at com.strobel.decompiler.languages.java.ast.CompilationUnit.acceptVisitor(CompilationUnit.java:81)
	at com.strobel.decompiler.languages.java.ast.transforms.EclipseEnumSwitchRewriterTransform.run(EclipseEnumSwitchRewriterTransform.java:44)
	at com.strobel.decompiler.languages.java.ast.transforms.TransformationPipeline.runTransformationsUntil(TransformationPipeline.java:91)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.runTransformations(AstBuilder.java:99)
	at com.strobel.decompiler.languages.java.JavaLanguage.runTransforms(JavaLanguage.java:97)
	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:72)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
	at us.deathmarine.luyten.DecompilerLinkProvider.generateContent(DecompilerLinkProvider.java:97)
	at us.deathmarine.luyten.OpenFile.decompileWithNavigationLinks(OpenFile.java:469)
	at us.deathmarine.luyten.OpenFile.decompile(OpenFile.java:442)
	at us.deathmarine.luyten.Model.extractClassToTextPane(Model.java:400)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:319)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:246)
```

**Comment by deathmarine** [comment]
Procyon errors are being closed.
