### ISSUE TITLE
Unable to open file, Wrong magic number

### ISSUE THREAD

**Issue by Infinitay** [deathmarine/Luyten#82]
java.lang.IllegalStateException: Wrong magic number: 52
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:337)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

**Comment by greenozon** [comment]
The first thing a JVM does when it loads a class is check that the first four bytes are (in hex) CA FE BA BE. This is the "magic number" and thats why you are getting that error, you are trying to load a file that isnt a class and so the class loader in the JVM is throwing out that exception.

**Comment by deathmarine** [comment]
#76, #64,  I would say the jar is either corrupt, or the class could be encrypted, the software could be decrypting classes and loading them later as a sort of obfuscation.  Either way I can only reproduce this intentionally, by renaming a binary file to class and putting it in a jar. 
You may have to do a little more investigation, look for a class extending Classloader and pulling resources from the jar. I once wrote a wrapper that would decrypt  and load each class and after phoning home and authenticating with a public and private key. Either way there is something else going on here.
