### ISSUE TITLE
java.lang.IllegalArgumentException: Argument 'type' cannot be null.

### ISSUE THREAD

**Issue by xtuul** [deathmarine/Luyten#87]
`java.lang.IllegalArgumentException: Argument 'type' cannot be null.
	at com.strobel.core.VerifyArgument.notNull(VerifyArgument.java:37)
	at com.strobel.assembler.ir.attributes.LocalVariableTableEntry.<init>(LocalVariableTableEntry.java:41)
	at com.strobel.assembler.ir.MetadataReader.readAttributeCore(MetadataReader.java:180)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:260)
	at com.strobel.assembler.ir.MetadataReader.readAttribute(MetadataReader.java:50)
	at com.strobel.assembler.ir.MetadataReader.readAttributes(MetadataReader.java:40)
	at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:202)
	at com.strobel.assembler.ir.MetadataReader.inflateAttribute(MetadataReader.java:368)
	at com.strobel.assembler.ir.MetadataReader.inflateAttributes(MetadataReader.java:345)
	at com.strobel.assembler.metadata.ClassFileReader.defineMethods(ClassFileReader.java:977)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:440)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:365)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
	at com.strobel.assembler.metadata.MetadataSystem.resolveCore(MetadataSystem.java:76)
	at com.strobel.assembler.metadata.MetadataResolver.resolve(MetadataResolver.java:104)
	at com.strobel.assembler.metadata.CoreMetadataFactory$UnresolvedType.resolve(CoreMetadataFactory.java:614)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:274)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:153)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:149)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createParameters(AstBuilder.java:161)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createMethod(AstBuilder.java:642)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:532)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:499)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:141)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:130)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addType(AstBuilder.java:105)
	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:71)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
	at us.deathmarine.luyten.DecompilerLinkProvider.generateContent(DecompilerLinkProvider.java:97)
	at us.deathmarine.luyten.OpenFile.decompileWithNavigationLinks(OpenFile.java:469)
	at us.deathmarine.luyten.OpenFile.decompile(OpenFile.java:442)
	at us.deathmarine.luyten.Model.extractClassToTextPane(Model.java:420)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:339)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)
`

**Comment by deathmarine** [comment]
Duplicate #86
