### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: sun/misc/URLClassPath

### ISSUE THREAD

**Issue by KOLANICH** [deathmarine/Luyten#90]
```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: sun/misc/URLClassPath
        at com.strobel.assembler.metadata.ClasspathTypeLoader.<init>(ClasspathTypeLoader.java:66)
        at com.strobel.assembler.metadata.ClasspathTypeLoader.<init>(ClasspathTypeLoader.java:42)
        at com.strobel.assembler.InputTypeLoader.<init>(InputTypeLoader.java:45)
        at us.deathmarine.luyten.LuytenTypeLoader.<init>(LuytenTypeLoader.java:15)
        at us.deathmarine.luyten.Model.<clinit>(Model.java:80)
        at us.deathmarine.luyten.MainWindow.<init>(MainWindow.java:87)
        at us.deathmarine.luyten.Luyten$1.run(Luyten.java:61)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:759)
        at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:712)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:88)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:729)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: sun.misc.URLClassPath
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:533)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:186)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:476)
        ... 21 more
```

with both openjdk-9-jdk and openjdk-8-jdk on Ubuntu Zesty. Is it openjdk bug or luyten one?

**Comment by deathmarine** [comment]
This is saying that you don't have the default java class loaded or can't be found. From the stacktrace its a class that Procyon needs to decompile.

**Comment by shanempope** [comment]
This occurs on OSX with a default Java 9 JDK.
If you run into this I suggest installing the Java 8 JDK and then switching to it via
https://stackoverflow.com/a/40754792/548975
