### ISSUE TITLE
unable to open file

### ISSUE THREAD

**Issue by wuyb123** [deathmarine/Luyten#91]
java.lang.IllegalStateException: Wrong magic number: 1397965647
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:337)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

**Comment by FireMasterK** [comment]
Post jar / class?

**Comment by greenozon** [comment]
@wuyb123
your input is not a valid class file :)

the error says it in a very clear manner - wrong magic (magic is a class file signature)

**Comment by wuyb123** [comment]
@greenozon  maybe an encrypted file

**Comment by greenozon** [comment]
why not? :) so where is your input file?

**Comment by deathmarine** [comment]
Run the file through a hex viewer/explorer/editor. There are a few good ones out there. I wouldn't put weird obfuscation / encryption past anything considering you are trying to reverse engineer it.
