### ISSUE TITLE
Unable to Decompile file!

### ISSUE THREAD

**Issue by Sprax2013** [deathmarine/Luyten#95]
Version: 0.5.3

First:
```
java.lang.NullPointerException
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:324)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:153)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:149)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createField(AstBuilder.java:602)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:524)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:499)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:141)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:130)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createMethod(AstBuilder.java:650)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:532)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:499)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:141)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:130)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createMethod(AstBuilder.java:650)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:532)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:499)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:141)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:130)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addType(AstBuilder.java:105)
	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:71)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
	at us.deathmarine.luyten.FileSaver.doSaveJarDecompiled(FileSaver.java:192)
	at us.deathmarine.luyten.FileSaver.access$300(FileSaver.java:45)
	at us.deathmarine.luyten.FileSaver$4.run(FileSaver.java:112)
	at java.lang.Thread.run(Unknown Source)
```

Second:
```
java.lang.NullPointerException
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:324)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:153)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:149)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createField(AstBuilder.java:602)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:524)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:499)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:141)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:130)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createMethod(AstBuilder.java:650)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:532)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:499)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:141)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:130)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addType(AstBuilder.java:105)
	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:71)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
	at us.deathmarine.luyten.FileSaver.doSaveJarDecompiled(FileSaver.java:192)
	at us.deathmarine.luyten.FileSaver.access$300(FileSaver.java:45)
	at us.deathmarine.luyten.FileSaver$4.run(FileSaver.java:112)
	at java.lang.Thread.run(Unknown Source)
```

Third: 
```
java.lang.NullPointerException
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:324)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:153)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.convertType(AstBuilder.java:149)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createField(AstBuilder.java:602)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addTypeMembers(AstBuilder.java:524)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeCore(AstBuilder.java:499)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createTypeNoCache(AstBuilder.java:141)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.createType(AstBuilder.java:130)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.addType(AstBuilder.java:105)
	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:71)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
	at us.deathmarine.luyten.FileSaver.doSaveJarDecompiled(FileSaver.java:192)
	at us.deathmarine.luyten.FileSaver.access$300(FileSaver.java:45)
	at us.deathmarine.luyten.FileSaver$4.run(FileSaver.java:112)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by deathmarine** [comment]
Procyon errors are being closed.
