### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1

### ISSUE THREAD

**Issue by hack0mate** [deathmarine/Luyten#96]
```
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1
	at java.util.Vector.get(Vector.java:748)
	at com.strobel.assembler.metadata.MetadataResolver.resolve(MetadataResolver.java:82)
	at com.strobel.assembler.metadata.CoreMetadataFactory$UnresolvedType.resolve(CoreMetadataFactory.java:614)
	at com.strobel.assembler.metadata.MetadataHelper.isEnclosedBy(MetadataHelper.java:60)
	at com.strobel.assembler.metadata.MetadataHelper.isEnclosedBy(MetadataHelper.java:76)
	at com.strobel.assembler.metadata.MetadataHelper.isEnclosedBy(MetadataHelper.java:76)
	at com.strobel.assembler.metadata.MetadataHelper.isEnclosedBy(MetadataHelper.java:76)
	at com.strobel.assembler.metadata.MetadataHelper.isEnclosedBy(MetadataHelper.java:76)
	at com.strobel.assembler.metadata.MetadataHelper.isEnclosedBy(MetadataHelper.java:76)
	at com.strobel.assembler.metadata.MetadataHelper.isEnclosedBy(MetadataHelper.java:76)
	at com.strobel.assembler.metadata.MetadataHelper.isEnclosedBy(MetadataHelper.java:76)
	at com.strobel.decompiler.languages.java.ast.transforms.EliminateSyntheticAccessorsTransform.visitInvocationExpression(EliminateSyntheticAccessorsTransform.java:86)
	at com.strobel.decompiler.languages.java.ast.transforms.EliminateSyntheticAccessorsTransform.visitInvocationExpression(EliminateSyntheticAccessorsTransform.java:35)
	at com.strobel.decompiler.languages.java.ast.InvocationExpression.acceptVisitor(InvocationExpression.java:68)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitVariableInitializer(DepthFirstAstVisitor.java:186)
	at com.strobel.decompiler.languages.java.ast.VariableInitializer.acceptVisitor(VariableInitializer.java:80)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitVariableDeclaration(DepthFirstAstVisitor.java:181)
	at com.strobel.decompiler.languages.java.ast.VariableDeclarationStatement.acceptVisitor(VariableDeclarationStatement.java:111)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitBlockStatement(DepthFirstAstVisitor.java:96)
	at com.strobel.decompiler.languages.java.ast.BlockStatement.acceptVisitor(BlockStatement.java:72)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitConstructorDeclaration(DepthFirstAstVisitor.java:216)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitConstructorDeclaration(ContextTrackingVisitor.java:75)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitConstructorDeclaration(ContextTrackingVisitor.java:28)
	at com.strobel.decompiler.languages.java.ast.ConstructorDeclaration.acceptVisitor(ConstructorDeclaration.java:57)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitTypeDeclaration(DepthFirstAstVisitor.java:236)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclaration(ContextTrackingVisitor.java:52)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclaration(ContextTrackingVisitor.java:28)
	at com.strobel.decompiler.languages.java.ast.TypeDeclaration.acceptVisitor(TypeDeclaration.java:90)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:33)
	at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitCompilationUnit(DepthFirstAstVisitor.java:241)
	at com.strobel.decompiler.languages.java.ast.CompilationUnit.acceptVisitor(CompilationUnit.java:81)
	at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.run(ContextTrackingVisitor.java:84)
	at com.strobel.decompiler.languages.java.ast.transforms.EliminateSyntheticAccessorsTransform.run(EliminateSyntheticAccessorsTransform.java:55)
	at com.strobel.decompiler.languages.java.ast.transforms.TransformationPipeline.runTransformationsUntil(TransformationPipeline.java:91)
	at com.strobel.decompiler.languages.java.ast.AstBuilder.runTransformations(AstBuilder.java:99)
	at com.strobel.decompiler.languages.java.JavaLanguage.runTransforms(JavaLanguage.java:97)
	at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:72)
	at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
	at us.deathmarine.luyten.Model$9.run(Model.java:977)

**Comment by deathmarine** [comment]
Procyon errors are being closed.
