### ISSUE TITLE
"Error in opening zip file"

### ISSUE THREAD

**Issue by Irrelevancies** [deathmarine/Luyten#97]
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at us.deathmarine.luyten.Model$4.run(Model.java:627)
	at java.lang.Thread.run(Unknown Source

**Comment by deathmarine** [comment]
Can you describe the error in more detail?
Luyten supports jar, zip and class extensions, I've always planned to do ear and war but haven't got around to it. https://github.com/deathmarine/Luyten/blob/master/src/us/deathmarine/luyten/Model.java#L318

I've tested this by renaming a Jar (which is a zip) to zip extension and it open file.
What is the directory structure of the zip you're trying to open, the zip is corrupt or a jar within a zip? Can you open the zip with any zip client like 7zip?
